# Generated by Django 4.2 on 2024-06-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Telegram', 'Telegram'), ('Gmail', 'Gmail'), ('Phone', 'Phone')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('link', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=255, null=True)),
                ('invitation_link', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(default=0)),
                ('access_level', models.CharField(choices=[('Allowed', 'Allowed'), ('Unallowable', 'Unallowable')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('text', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open')], default='Open', max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('telegram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VipAccountAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramTicketAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramticket')),
            ],
        ),
    ]
