# Generated by Django 4.2 on 2024-06-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportaccount',
            options={'verbose_name': 'حساب های پشتیبانی', 'verbose_name_plural': 'حساب های پشتیبانی'},
        ),
        migrations.AlterModelOptions(
            name='telegramchannels',
            options={'verbose_name': 'لینک های ربات', 'verbose_name_plural': 'لینک های ربات'},
        ),
        migrations.AlterModelOptions(
            name='telegramprofile',
            options={'verbose_name': 'کابران', 'verbose_name_plural': 'کابران'},
        ),
        migrations.AlterModelOptions(
            name='telegramticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت'},
        ),
        migrations.AlterModelOptions(
            name='telegramticketanswer',
            options={'verbose_name': 'پاسخ تیکت', 'verbose_name_plural': 'پاسخ تیکت'},
        ),
        migrations.AlterModelOptions(
            name='vipaccountamount',
            options={'verbose_name': 'اشتراک ویژه', 'verbose_name_plural': 'اشتراک ویژه'},
        ),
    ]
