# Generated by Django 4.2 on 2024-06-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_supportaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannels',
            name='title',
            field=models.CharField(choices=[('Forex', 'سیگنال فارکس'), ('Crypto', 'سیگنال کریپتو'), ('TraderBot', 'ربات های تریدر'), ('Broker', 'ثبت نام بروکر'), ('Bonus', 'بونوس')], max_length=25),
        ),
    ]
