# Generated by Django 4.2 on 2024-06-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_telegramchannels_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannels',
            name='title',
            field=models.CharField(choices=[('Forex', 'سیگنال فارکس'), ('Crypto', 'سیگنال کریپتو'), ('TraderBot', 'ربات های تریدر'), ('Broker', 'ثبت نام بروکر'), ('Bonus', 'بونوس'), ('PotentialCurrencies', 'ارزهای پر پتانسیل'), ('Airdrop', 'ایردراپ ها'), ('Eduction', 'آموزش')], max_length=25),
        ),
        migrations.AlterField(
            model_name='telegramticket',
            name='title',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
