# Generated by Django 4.2 on 2024-06-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_supportaccount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportaccount',
            name='platform',
            field=models.CharField(choices=[('Telegram', 'تلگرام'), ('Gmail', 'ایمیل'), ('Phone', 'تلفن')], max_length=20),
        ),
    ]
