# Generated by Django 4.2 on 2024-06-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_alter_supportaccount_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'تنظیمات بات',
                'verbose_name_plural': 'تنظیمات بات',
            },
        ),
        migrations.AddField(
            model_name='vipaccountamount',
            name='expired',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
